#!/bin/sh

change(){
find "$1"  -regex ".*/[^$new]*" - type f -exec sh -c ' file2="{}" \
oldFile=$(basename "$file2"); newFile=`echo "$oldFile" | tr [$old] [$new]`\
path=$(dirname "$file2") \
if [ -f "$path"/"$newFile" ] ; then \
echo "kolize" >&2\
else mv "{}" "$path"/"$newFile" \
fi
'



if [ "$1" = "-r" ]; then
    old="a-z"
    new="A-Z"
    shift
else
    old="A-Z"
    new="a-z"
fi

if [ "$#" == 0 ]; then
    change "./"
fi

for file
do 
change $file
done